# SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
path_classifiers:
    library:
        - build/_install
        - build/_prefix
    test:
        - tests
    exclude:
        - tests/input
        - tests/new_input
